language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

osx_image: xcode7.3
sudo: true
dist: trusty

env:
  global:
    - ERT_SHOW_BACKTRACE=1
    - INSTALL_DIR="$(pwd)/install"
    - LD_LIBRARY_PATH=" "${INSTALL_DIR}/lib:${INSTALL_DIR}/lib64"
  matrix:
    - PYTHON_VERSION=2.7 TEST_SUITE="-LE SLOW"  # Run all tests not labeled as slow
    - PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_1" # Run all tests labeled as SLOW in group 1
    - PYTHON_VERSION=2.7 TEST_SUITE="-L SLOW_2" # Run all tests labeled as SLOW in group 2
    - PYTHON_VERSION=3.6                        # Run all tests

matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - liblapack-dev
    - valgrind
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - cmake-data


install:
  - if [[ "$CC" == "gcc" ]]; then export CXX="g++-4.8"; fi
  - sudo pip install --upgrade -r requirements.txt

script:
  - mkdir build
  - pushd build
  - cmake .. -DBUILD_TESTS=ON
             -DENABLE_PYTHON=ON
             -DINSTALL_CWRAP=OFF
             -DBUILD_APPLICATIONS=ON
             -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
             -DINSTALL_ERT_LEGACY=ON
             -DCMAKE_PREFIX_PATH=$INSTALL_DIR
             -DERT_USE_OPENMP=ON
             -DCMAKE_C_FLAGS='-Werror=all'
             -DCMAKE_CXX_FLAGS='-Werror -Wno-unused-result'
  - make
  - make install
  - export PYTHONPATH=$INSTALL_DIR/lib/python2.7/dist-packages:$INSTALL_DIR/lib64/python2.7/dist-packages:$PYTHONPATH
  - export PYTHONPATH=$INSTALL_DIR/lib/python2.7/site-packages:$INSTALL_DIR/lib64/python2.7/site-packages:$PYTHONPATH
  - set -e; python -c "import ecl"; set +e
  - ctest --output-on-failure $TEST_SUITE
